import type { NextPage } from "next"
import Head from "next/head"
import Menu from "../components/Menu"
import MenuIcon from "../components/MenuIcon"
import Home from "../sections/Home"
import { useMenu } from "../store/providers/menuProvider"

const Index: NextPage = () => {
  const { menuVis } = useMenu()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuIcon />
      {menuVis && <Menu />}
      <Home />
    </div>
  )
}

export default Index
